# Generated by Django 5.0.2 on 2024-03-15 16:05

import ckeditor_uploader.fields
import django.db.models.deletion
import furniture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Complect_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=30)),
                ('sale_price', models.DecimalField(decimal_places=3, max_digits=30)),
                ('real_price', models.DecimalField(decimal_places=3, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Complect_product',
                'verbose_name_plural': 'Complect_products',
                'db_table': 'Complect_product',
            },
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='furniture')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[furniture.models.full_name])),
                ('phone_number', models.CharField(max_length=13, validators=[furniture.models.validate_phone_number])),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Xonalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
                'db_table': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description')),
                ('height', models.PositiveIntegerField(default=0)),
                ('length', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=3, max_digits=30, verbose_name='price')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='sale_price')),
                ('real_price', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='furniture.category')),
                ('img', models.ManyToManyField(related_name='product_img', to='furniture.img')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('comlect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.complect_product')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'Order_Item',
            },
        ),
        migrations.AddField(
            model_name='complect_product',
            name='product',
            field=models.ManyToManyField(related_name='complect_product', to='furniture.product'),
        ),
        migrations.AddField(
            model_name='complect_product',
            name='xonalar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.xonalar'),
        ),
    ]
