# Generated by Django 5.0.2 on 2024-02-27 18:01

import django.db.models.deletion
import furniture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[furniture.models.full_name])),
                ('phone_number', models.CharField(max_length=13, validators=[furniture.models.validate_phone_number])),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.order'),
        ),
    ]
