# Generated by Django 5.0.2 on 2024-03-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complect_product',
            name='xonalar',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='furniture.xonalar'),
            preserve_default=False,
        ),
    ]
