# Generated by Django 5.0.2 on 2024-02-28 20:19

import furniture.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[furniture.models.validate_phone_number]),
        ),
    ]
