# Generated by Django 5.0.2 on 2024-03-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_remove_product_img_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complect_product',
            name='product',
            field=models.ManyToManyField(related_name='complect_product', to='furniture.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='furniture.category'),
        ),
    ]
