# Generated by Django 5.0.2 on 2024-03-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_alter_complect_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complect_product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='complect_product',
            name='real_sale_price',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='complect_product',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ManyToManyField(related_name='product_img', to='furniture.img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=30, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='sale_price'),
        ),
    ]
