# Generated by Django 5.0.2 on 2024-03-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_alter_complect_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
