# Generated by Django 5.0.2 on 2024-03-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0006_alter_product_height_alter_product_length_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complect_product',
            old_name='real_sale_price',
            new_name='real_price',
        ),
    ]
