# Generated by Django 5.0.2 on 2024-03-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0007_rename_real_sale_price_complect_product_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comlect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='furniture.complect_product'),
        ),
    ]
