# Generated by Django 5.0.2 on 2024-02-27 01:16

import address.models
import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[api.models.full_name])),
                ('phone_number', models.CharField(max_length=13, validators=[api.models.validate_phone_number])),
                ('email', models.EmailField(max_length=254)),
                ('adress', address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.address')),
            ],
        ),
    ]
